export * from "../shared";

import {
  ActivitiesResourceQuerySchema,
  AboutResourceSchema,
  ActivityProfileDocumentListingQuerySchema,
  ActivityProfileDocumentQuerySchema,
  ActivitySchema,
  AgentAccountSchema,
  AgentsResourceQuerySchema,
  AgentProfileDocumentListingQuerySchema,
  AgentProfileDocumentQuerySchema,
  AgentSchema,
  AttachmentSchema,
  ContextActivitiesSchema,
  ContextSchema,
  GroupSchema,
  InteractionComponentSchema,
  InteractionTypeSchema,
  Iso8601DurationSchema,
  Iso8601TimestampSchema,
  LanguageMapSchema,
  LanguageTagSchema,
  NonEmptyStringSchema,
  PersonSchema,
  ResultSchema,
  ScoreSchema,
  StatementsQuerySchema,
  StatementObjectSchema,
  StatementResultSchema,
  StatementRefSchema,
  StatementSchema,
  StatementSubmissionSchema,
  StateDocumentListingQuerySchema,
  StateDocumentQuerySchema,
  SubStatementSchema,
  UuidSchema,
  VerbSchema,
  XapiDocumentSchema,
  XapiDocumentIdListSchema,
  IriSchema,
  XapiVersionSchema,
  XapiHttpMethodSchema,
  XapiResourceSchema,
  XapiRequestHeaderSchema,
  XapiResponseHeaderSchema,
  XapiErrorCodeSchema,
  XapiErrorResponseSchema,
  XapiConcurrencySchema,
  XapiMultipartAttachmentPartSchema,
  XapiMultipartRequestSchema,
} from "../shared";

export const XapiV1_0_3 = {
  Schemas: {
    AgentAccount: AgentAccountSchema,
    Agent: AgentSchema,
    Group: GroupSchema,
    Verb: VerbSchema,
    InteractionComponent: InteractionComponentSchema,
    Activity: ActivitySchema,
    StatementRef: StatementRefSchema,
    SubStatement: SubStatementSchema,
    Score: ScoreSchema,
    Result: ResultSchema,
    ContextActivities: ContextActivitiesSchema,
    Context: ContextSchema,
    Attachment: AttachmentSchema,
    StatementObject: StatementObjectSchema,
    Statement: StatementSchema,
    StatementSubmission: StatementSubmissionSchema,
    StatementResult: StatementResultSchema,
    Person: PersonSchema,
    AboutResource: AboutResourceSchema,
    StatementsQuery: StatementsQuerySchema,
    AgentsResourceQuery: AgentsResourceQuerySchema,
    ActivitiesResourceQuery: ActivitiesResourceQuerySchema,
    StateDocumentQuery: StateDocumentQuerySchema,
    StateDocumentListingQuery: StateDocumentListingQuerySchema,
    AgentProfileDocumentQuery: AgentProfileDocumentQuerySchema,
    AgentProfileDocumentListingQuery: AgentProfileDocumentListingQuerySchema,
    ActivityProfileDocumentQuery: ActivityProfileDocumentQuerySchema,
    ActivityProfileDocumentListingQuery: ActivityProfileDocumentListingQuerySchema,
    XapiDocument: XapiDocumentSchema,
    XapiDocumentIdList: XapiDocumentIdListSchema,
    HttpMethod: XapiHttpMethodSchema,
    Resource: XapiResourceSchema,
    RequestHeader: XapiRequestHeaderSchema,
    ResponseHeader: XapiResponseHeaderSchema,
    ErrorCode: XapiErrorCodeSchema,
    ErrorResponse: XapiErrorResponseSchema,
    Concurrency: XapiConcurrencySchema,
    MultipartAttachmentPart: XapiMultipartAttachmentPartSchema,
    MultipartRequest: XapiMultipartRequestSchema,
  },

  Shared: {
    Uuid: UuidSchema,
    Version: XapiVersionSchema,
    Iri: IriSchema,
    LanguageTag: LanguageTagSchema,
    LanguageMap: LanguageMapSchema,
    Timestamp: Iso8601TimestampSchema,
    Duration: Iso8601DurationSchema,
    NonEmptyString: NonEmptyStringSchema,
    InteractionType: InteractionTypeSchema,
  },
} as const;

export type XapiV1_0_3Schemas = typeof XapiV1_0_3.Schemas;

export const XapiV1_0_3DerivedZodTemplates = {
  description:
    "xAPI 1.0.3 Zod schemas for statements, statement result/person objects, document resources, LRS transport, and about metadata",
  specLinks: {
    about: "https://github.com/adlnet/xAPI-Spec/blob/ca782a1129bc6ae848640ff4e8e262334bdd0ba5/xAPI-About.md",
    data: "https://github.com/adlnet/xAPI-Spec/blob/ca782a1129bc6ae848640ff4e8e262334bdd0ba5/xAPI-Data.md",
    communication:
      "https://github.com/adlnet/xAPI-Spec/blob/ca782a1129bc6ae848640ff4e8e262334bdd0ba5/xAPI-Communication.md",
    lrsContent:
      "https://github.com/adlnet/xAPI-Spec/blob/ca782a1129bc6ae848640ff4e8e262334bdd0ba5/xAPI-Communication.md#lrs",
  },
  scope:
    "Statements, statement-like objects, statement result/person objects, statement and resource queries, LRS document resources and id lists, transport headers, concurrency control, multipart attachment handling, and about/version metadata",
  designNotes: [
    "Structured statement data is modeled strictly; document bodies are intentionally permissive because xAPI allows arbitrary document content types.",
    "Agent and Group validators require at least one identifier or member list, matching the data model intent rather than relying on shape alone.",
    "The transport- and header-level parts of the spec are represented as helper schemas rather than being forced into a single statement object.",
    "Concurrency control (ETags, If-Match/If-None-Match) and multipart attachment transmission are modeled as separate concerns for flexibility.",
    "Error codes and response envelopes follow HTTP semantics with explicit status codes and optional detail messaging.",
  ],
  coreSchemas: [
    "Agent",
    "Group",
    "Verb",
    "Activity",
    "SubStatement",
    "Result",
    "Context",
    "Attachment",
    "Statement",
    "StatementResult",
    "Person",
    "AboutResource",
    "StatementsQuery",
    "AgentsResourceQuery",
    "ActivitiesResourceQuery",
    "StateDocumentQuery",
    "StateDocumentListingQuery",
    "AgentProfileDocumentQuery",
    "AgentProfileDocumentListingQuery",
    "ActivityProfileDocumentQuery",
    "ActivityProfileDocumentListingQuery",
    "XapiDocumentIdList",
    "HttpMethod",
    "Resource",
    "RequestHeader",
    "ResponseHeader",
    "ErrorCode",
    "ErrorResponse",
    "Concurrency",
    "MultipartAttachmentPart",
    "MultipartRequest",
  ],
} as const;

export const Schemas = XapiV1_0_3.Schemas;
export const Shared = XapiV1_0_3.Shared;
export const DerivedZodTemplates = XapiV1_0_3DerivedZodTemplates;
