export type CaliperRequirementSource = "textual-spec-v1p2" | "textual-spec-v1p2-impl" | "bootcamp-v1_2";

export const CALIPER_REQUIREMENT_SOURCE_PRECEDENCE = [
  "textual-spec-v1p2",
  "textual-spec-v1p2-impl",
  "bootcamp-v1_2",
] as const;

export const CALIPER_REQUIREMENT_SOURCES = {
  textualSpecV12: "https://www.imsglobal.org/spec/caliper/v1p2",
  textualImplGuideV12: "https://www.imsglobal.org/spec/caliper/v1p2/impl/",
  caliperSpecMarkdown:
    "https://raw.githubusercontent.com/1EdTech/caliper-spec/1849e118b47acb24a6d97f976fe72fc2f5182570/caliper-spec.md",
  bootcampSchemas: "https://github.com/1EdTech/CaliperBootcamp/tree/main/schemas/v1_2",
} as const;

export interface CaliperTextualEventRule {
  profile: string;
  supportedActors: readonly string[];
  supportedActions: readonly string[];
  deprecatedActions: readonly string[];
  supportedObjects: readonly string[];
  supportedGeneratedEntities: readonly string[];
  supportedTargetEntities: readonly string[];
  source: CaliperRequirementSource;
}

export const CALIPER_TEXTUAL_EVENT_RULES: Record<string, CaliperTextualEventRule> = {
  AnnotationEvent: {
    profile: "AnnotationProfile",
    supportedActors: ["Person"],
    supportedActions: ["Bookmarked", "Highlighted", "Shared", "Tagged"],
    deprecatedActions: [
      "Attached",
      "Classified",
      "Commented",
      "Described",
      "Disliked",
      "Identified",
      "Liked",
      "Linked",
      "Questioned",
      "Ranked",
      "Recommended",
      "Subscribed",
    ],
    supportedObjects: ["DigitalResource"],
    supportedGeneratedEntities: [
      "Annotation",
      "BookmarkAnnotation",
      "HighlightAnnotation",
      "SharedAnnotation",
      "TagAnnotation",
    ],
    supportedTargetEntities: [],
    source: "textual-spec-v1p2",
  },
  AssessmentEvent: {
    profile: "AssessmentProfile",
    supportedActors: ["Person"],
    supportedActions: ["Started", "Paused", "Resumed", "Restarted", "Reset", "Submitted"],
    deprecatedActions: [],
    supportedObjects: ["Assessment"],
    supportedGeneratedEntities: ["Attempt"],
    supportedTargetEntities: [],
    source: "textual-spec-v1p2",
  },
  AssessmentItemEvent: {
    profile: "AssessmentProfile",
    supportedActors: ["Person"],
    supportedActions: ["Started", "Skipped", "Completed"],
    deprecatedActions: ["Reviewed", "Viewed"],
    supportedObjects: ["AssessmentItem"],
    supportedGeneratedEntities: [
      "Response",
      "FillinBlankResponse",
      "MultipleChoiceResponse",
      "MultipleResponseResponse",
      "SelectTextResponse",
      "TrueFalseResponse",
    ],
    supportedTargetEntities: [],
    source: "textual-spec-v1p2",
  },
  AssignableEvent: {
    profile: "AssignableProfile",
    supportedActors: ["Person"],
    supportedActions: ["Activated", "Deactivated", "Started", "Completed", "Submitted", "Reviewed"],
    deprecatedActions: ["Abandoned", "Hid", "Showed"],
    supportedObjects: ["AssignableDigitalResource"],
    supportedGeneratedEntities: ["Attempt"],
    supportedTargetEntities: [],
    source: "textual-spec-v1p2",
  },
  ForumEvent: {
    profile: "ForumProfile",
    supportedActors: ["Person"],
    supportedActions: ["Subscribed", "Unsubscribed"],
    deprecatedActions: [],
    supportedObjects: ["Forum"],
    supportedGeneratedEntities: [],
    supportedTargetEntities: [],
    source: "textual-spec-v1p2",
  },
  GradeEvent: {
    profile: "GradingProfile",
    supportedActors: ["Agent"],
    supportedActions: ["Graded"],
    deprecatedActions: [],
    supportedObjects: ["Attempt"],
    supportedGeneratedEntities: ["Score"],
    supportedTargetEntities: [],
    source: "textual-spec-v1p2",
  },
  MediaEvent: {
    profile: "MediaProfile",
    supportedActors: ["Person"],
    supportedActions: [
      "Started",
      "Ended",
      "Paused",
      "Resumed",
      "Restarted",
      "ForwardedTo",
      "JumpedTo",
      "ChangedResolution",
      "ChangedSize",
      "ChangedSpeed",
      "ChangedVolume",
      "EnabledClosedCaptioning",
      "DisabledClosedCaptioning",
      "EnteredFullScreen",
      "ExitedFullScreen",
      "Muted",
      "Unmuted",
      "OpenedPopout",
      "ClosedPopout",
    ],
    deprecatedActions: ["Rewound"],
    supportedObjects: ["AudioObject", "ImageObject", "MediaObject", "VideoObject"],
    supportedGeneratedEntities: [],
    supportedTargetEntities: ["MediaLocation"],
    source: "textual-spec-v1p2",
  },
  MessageEvent: {
    profile: "ForumProfile",
    supportedActors: ["Person"],
    supportedActions: ["MarkedAsRead", "MarkedAsUnRead", "Posted"],
    deprecatedActions: [],
    supportedObjects: ["Message"],
    supportedGeneratedEntities: [],
    supportedTargetEntities: [],
    source: "textual-spec-v1p2",
  },
  NavigationEvent: {
    profile: "ReadingProfile",
    supportedActors: ["Person"],
    supportedActions: ["NavigatedTo"],
    deprecatedActions: [],
    supportedObjects: ["DigitalResource", "SoftwareApplication"],
    supportedGeneratedEntities: ["Result"],
    supportedTargetEntities: ["Frame"],
    source: "textual-spec-v1p2",
  },
  SessionEvent: {
    profile: "SessionProfile",
    supportedActors: ["Person", "SoftwareApplication"],
    supportedActions: ["LoggedIn", "LoggedOut", "TimedOut"],
    deprecatedActions: [],
    supportedObjects: ["Session", "SoftwareApplication"],
    supportedGeneratedEntities: [],
    supportedTargetEntities: [],
    source: "textual-spec-v1p2",
  },
  ThreadEvent: {
    profile: "ForumProfile",
    supportedActors: ["Person"],
    supportedActions: ["MarkedAsRead", "MarkedAsUnRead"],
    deprecatedActions: [],
    supportedObjects: ["Thread"],
    supportedGeneratedEntities: [],
    supportedTargetEntities: [],
    source: "textual-spec-v1p2",
  },
  ToolUseEvent: {
    profile: "ToolUseProfile",
    supportedActors: ["Person"],
    supportedActions: ["Used"],
    deprecatedActions: [],
    supportedObjects: ["SoftwareApplication"],
    supportedGeneratedEntities: [],
    supportedTargetEntities: [],
    source: "textual-spec-v1p2",
  },
  ViewEvent: {
    profile: "ReadingProfile",
    supportedActors: ["Person"],
    supportedActions: ["Viewed"],
    deprecatedActions: [],
    supportedObjects: ["DigitalResource"],
    supportedGeneratedEntities: [],
    supportedTargetEntities: ["Frame"],
    source: "textual-spec-v1p2",
  },
};

export const CALIPER_BOOTCAMP_ONLY_EVENT_TYPES = [
  "Event",
  "FeedbackEvent",
  "OutcomeEvent",
  "QuestionnaireEvent",
  "QuestionnaireItemEvent",
  "ReadingEvent",
  "ResourceManagementEvent",
  "SearchEvent",
  "SurveyEvent",
  "SurveyInvitationEvent",
  "ToolLaunchEvent",
] as const;
