import { z } from "zod";

import { qti21Schemas } from "./schemas";

export const {
  QtiAssessmentItemDocumentSchema,
  QtiAssessmentItemRawSchema,
  QtiAssessmentItemRefSchema,
  QtiAssessmentItemSchema,
  QtiAssessmentSectionDocumentSchema,
  QtiAssessmentSectionRawSchema,
  QtiAssessmentSectionRefSchema,
  QtiAssessmentSectionSchema,
  QtiAssessmentTestDocumentSchema,
  QtiAssessmentTestRawSchema,
  QtiAssessmentTestSchema,
  QtiAssociateInteractionSchema,
  QtiBranchRuleSchema,
  QtiChoiceInteractionSchema,
  QtiExtendedTextInteractionSchema,
  QtiGapMatchInteractionSchema,
  QtiHotspotInteractionSchema,
  QtiHottextInteractionSchema,
  QtiInlineChoiceInteractionSchema,
  QtiItemBodyDocumentSchema,
  QtiItemBodySchema,
  QtiItemSessionControlSchema,
  QtiMatchInteractionSchema,
  QtiMediaInteractionSchema,
  QtiModalFeedbackDocumentSchema,
  QtiModalFeedbackSchema,
  QtiOrderingSchema,
  QtiOutcomeDeclarationDocumentSchema,
  QtiOutcomeDeclarationRawSchema,
  QtiOutcomeDeclarationSchema,
  QtiOutcomeProcessingDocumentSchema,
  QtiOutcomeProcessingSchema,
  QtiResponseDeclarationDocumentSchema,
  QtiResponseDeclarationRawSchema,
  QtiResponseDeclarationSchema,
  QtiResponseProcessingDocumentSchema,
  QtiResponseProcessingSchema,
  QtiRubricBlockSchema,
  QtiSelectionSchema,
  QtiTemplateDeclarationDocumentSchema,
  QtiTemplateDeclarationRawSchema,
  QtiTemplateDeclarationSchema,
  QtiTemplateProcessingDocumentSchema,
  QtiTemplateProcessingSchema,
  QtiTestFeedbackSchema,
  QtiTestPartSchema,
  QtiTextEntryInteractionSchema,
  QtiTimeLimitsSchema,
  QtiUploadInteractionSchema,
} = qti21Schemas;

export const QtiItemProfileDocumentSchema = z.union([
  QtiAssessmentItemDocumentSchema,
  QtiOutcomeDeclarationDocumentSchema,
  QtiResponseProcessingDocumentSchema,
]);

export const QtiTestProfileDocumentSchema = z.union([
  QtiAssessmentTestDocumentSchema,
  QtiAssessmentSectionDocumentSchema,
  QtiOutcomeDeclarationDocumentSchema,
  QtiOutcomeProcessingDocumentSchema,
]);
