export const capabilities = {
  contractVersion: "1.0.0",
  profileVersion: "1.0.0",
  adapterName: "cmi5-adapter-reference",
  adapterVersion: "0.1.0",
  profiles: ["cmi5-lms-v1"],
  operations: [
    "fixtures.provision",
    "cmi5.package.import",
    "cmi5.launch.create",
    "cmi5.launch.fetch",
    "cmi5.launch.data",
    "cmi5.au.statement.post",
    "cmi5.au.statement.get",
    "cmi5.registration.waive",
    "cmi5.session.abandon",
    "cmi5.state.reload",
  ],
  optionalFeatures: [
    "cmi5-fetch-auth-exchange",
    "cmi5-launch-data-resource",
    "cmi5-au-runtime-lifecycle",
    "cmi5-fetch-auth-hardening",
    "cmi5-auth-request-replay-protection",
    "cmi5-package-structure-validation",
    "cmi5-durable-state",
    "cmi5-cross-system-integration",
  ],
};
